package encoder

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"testing"

	pxar "github.com/pbs-plus/pxar"
	"github.com/pbs-plus/pxar/format"
)

// TestProbeEncodeManyCrosscheck encodes a 20-file directory plus a nested
// 5-file subdirectory and asserts byte-for-byte equality with the Rust
// reference output in testdata/rust_many.hex (generated by probe_encode_many).
// This stress-tests the goodbye-table binary tree array (BST) layout and
// relative-offset computation for many entries.
func TestProbeEncodeManyCrosscheck(t *testing.T) {
	rootMeta := &pxar.Metadata{Stat: mkStat(format.ModeIFDIR | 0o755)}
	buf := &bytes.Buffer{}
	enc := NewEncoder(buf, nil, rootMeta, nil)

	names := []string{
		"zeta", "alpha", "mike", "bravo", "yankee", "charlie", "delta", "echo",
		"foxtrot", "golf", "hotel", "india", "juliet", "kilo", "lima", "november",
		"oscar", "papa", "quebec", "romeo",
	}
	fileMeta := &pxar.Metadata{Stat: mkStat(format.ModeIFREG | 0o644)}
	for _, n := range names {
		if _, err := enc.AddFile(fileMeta, n, []byte(n)); err != nil {
			t.Fatal(err)
		}
	}

	subMeta := &pxar.Metadata{Stat: mkStat(format.ModeIFDIR | 0o755)}
	if err := enc.CreateDirectory("sub", subMeta); err != nil {
		t.Fatal(err)
	}
	for i := range 5 {
		name := fmt.Sprintf("f%d", i)
		if _, err := enc.AddFile(fileMeta, name, []byte(name)); err != nil {
			t.Fatal(err)
		}
	}
	if err := enc.Finish(); err != nil {
		t.Fatal(err)
	}
	if err := enc.Close(); err != nil {
		t.Fatal(err)
	}

	want, err := os.ReadFile("testdata/rust_many.hex")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	rustHex := strings.TrimSpace(string(want))
	goHex := hex(buf.Bytes())

	if goHex != rustHex {
		t.Errorf("length: go=%d rust=%d", len(buf.Bytes()), len(rustHex)/2)
		minLen := min(len(rustHex), len(goHex))
		for i := 0; i < minLen; i++ {
			if goHex[i] != rustHex[i] {
				t.Errorf("first hex diff at byte %d (hex-char %d):\n  go=  ...%s\n  rust=...%s",
					i/2, i, goHex[max(0, i-16):minLen], rustHex[max(0, i-16):minLen])
				break
			}
		}
	}
}
